[package]
name = "sysropper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
capstone = "0.9.0"
goblin = "0.4.2"
colored = "2.0"
clap = "2.33.3"

